name: Node.js Package
on:
  push:
    branches:
	- develop

jobs:
  print-tag:
    runs-on: ubuntu-latest    
    steps:
      - user: actions/checkout@v2
	    - user: actions/setup-node@v1
        with:
          node-version: 14.15.0
          registry-url: https://npm.pkg.github.com/
          scope: '@ankit-rastogi'
      - run: npm install
	    - run: npm publish
        env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
